# Generated by Django 5.0.6 on 2024-06-20 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=100, null=True, unique=True)),
                ("user_pw", models.CharField(blank=True, max_length=100, null=True)),
                ("user_gender", models.CharField(blank=True, max_length=10, null=True)),
                ("user_age", models.CharField(blank=True, max_length=10, null=True)),
                ("user_email", models.CharField(blank=True, max_length=100, null=True)),
                ("user_phone", models.CharField(blank=True, max_length=21, null=True)),
                ("enrolldate", models.DateField(blank=True, null=True)),
                ("delflag", models.CharField(blank=True, max_length=5, null=True)),
                ("faceid", models.TextField(blank=True, null=True)),
                ("user_qr", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "sub",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
            options={
                "db_table": "UserProfile",
                "managed": False,
            },
        ),
    ]
